- name: ds100
  inputs: /work/users/j/s/jsikder/fordan/ds100/
  output: /nas/longleaf/home/jsikder/introtracker/workflow/models
  model: createCNN
  ntaxa: 3
  loci_count: 100
  loci_length: 1200
  n_classes: 4
  n_channels: 1
  shuffle: True
  labelCorrection: 0
  batch_size: 1
  epochs: 50
  train_start: 0
  train_end: 29333
  val_start: 0
  val_end: 14665
---
- name: temp1
  inputs: /work/users/j/s/jsikder/fordan/temp2/
  output: /nas/longleaf/home/jsikder/introtracker/workflow/models
  model: createCNN
  ntaxa: 3
  loci_count: 100
  loci_length: 1200
  n_classes: 4
  n_channels: 1
  shuffle: True
  labelCorrection: 0
  batch_size: 1
  epochs: 50
  train_start: 0
  train_end: 500
  val_start: 0
  val_end: 300
---
- name: temp2
  inputs: /work/users/j/s/jsikder/fordan/temp4/
  output: /nas/longleaf/home/jsikder/introtracker/workflow/models
  model: createCNN
  ntaxa: 3
  loci_count: 100
  loci_length: 1200
  n_classes: 4
  n_channels: 1
  shuffle: True
  labelCorrection: 0
  batch_size: 1
  epochs: 50
  train_start: 0
  train_end: 500
  val_start: 0
  val_end: 300
---
- name: temp3
  inputs: /work/users/j/s/jsikder/fordan/temp3/
  output: /nas/longleaf/home/jsikder/introtracker/workflow/models
  ntaxa: 3
  loci_count: 100
  loci_length: 1200
  n_classes: 4
  n_channels: 1
  shuffle: True
  labelCorrection: 0
  batch_size: 1
  epochs: 5
  train_start: 0
  train_end: 500
  val_start: 0
  val_end: 100
---
- name: tree1
  inputs: /work/users/j/s/jsikder/fordan/tree1
  output: /nas/longleaf/home/jsikder/introtracker/workflow/models
  ntaxa: 3
  loci_count: 100
  loci_length: 1200
  n_classes: 4
  n_channels: 1
  shuffle: True
  labelCorrection: 0
  batch_size: 1
  epochs: 5
  train_start: 0
  train_end: 300
  val_start: 0
  val_end: 50
---
- name: tree2
  inputs: /work/users/j/s/jsikder/fordan/tree2
  output: /nas/longleaf/home/jsikder/introtracker/workflow/models
  ntaxa: 3
  loci_count: 100
  loci_length: 1200
  n_classes: 4
  n_channels: 1
  shuffle: True
  labelCorrection: 4
  batch_size: 1
  epochs: 5
  train_start: 0
  train_end: 300
  val_start: 0
  val_end: 50
---
- name: tree3
  inputs: /work/users/j/s/jsikder/fordan/tree3
  output: /nas/longleaf/home/jsikder/introtracker/workflow/models
  ntaxa: 3
  loci_count: 100
  loci_length: 1200
  n_classes: 4
  n_channels: 1
  shuffle: True
  labelCorrection: 7
  batch_size: 1
  epochs: 5
  train_start: 0
  train_end: 300
  val_start: 0
  val_end: 50
---
- name: tree4
  inputs: /work/users/j/s/jsikder/fordan/tree4
  output: /nas/longleaf/home/jsikder/introtracker/workflow/models
  ntaxa: 3
  loci_count: 100
  loci_length: 1200
  n_classes: 4
  n_channels: 1
  shuffle: True
  labelCorrection: 10
  batch_size: 1
  epochs: 5
  train_start: 0
  train_end: 300
  val_start: 0
  val_end: 50