- name: temptree
  data: datasets/treeMatrices/tree1_matrices.npy
  labels: datasets/treeLabels/temptree.txt
  batch_size: 1
  num_output_files: 3000
  shuffle: False
  output_dir: /work/users/j/s/jsikder/fordan/temp3
  output_dir_2: None
---
- name: tree1
  data: datasets/treeMatrices/tree1_matrices.npy
  labels: datasets/treeLabels/tree1.txt
  batch_size: 1
  num_output_files: 300
  shuffle: False
  output_dir: /work/users/j/s/jsikder/fordan/tree1
  output_dir_2: None